//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingVaksinService
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPOM_Log_Penggunaan_Vaksin
    {
        public int id { get; set; }
        public Nullable<int> id_RumahSakit { get; set; }
        public string no_registrasi { get; set; }
        public string No_RekMedis { get; set; }
        public string NIK { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
    }
}
