//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingVaksinService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Masyarakat
    {
        public string NIK { get; set; }
        public string Nama { get; set; }
        public string Alamat { get; set; }
        public string JK { get; set; }
        public Nullable<System.DateTime> TglLahir { get; set; }
        public string username { get; set; }
    }
}
