//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingVaksinService
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_Vaksin
    {
        public string no_registrasi { get; set; }
        public Nullable<int> id_rumahSakit { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
        public string kode_ref { get; set; }
        public Nullable<int> id_produsen { get; set; }
        public Nullable<int> isReported { get; set; }
        public string kemasan { get; set; }
        public Nullable<int> jumlah { get; set; }
    }
}
